### ISSUE TITLE
Fastformers/Transformers question

### ISSUE THREAD

**Issue by jmwoloso** [microsoft/fastformers#17]
Hello!

I was reading your paper and was looking in the HF repo and found https://github.com/huggingface/transformers/issues/8083 where it appeared that you were discussing adding your functionality to their library, however that never happened, so I am curious if you discovered something that prohibited adding this functionality. Thanks!

**Comment by ykim362** [comment]
Hi @jmwoloso.

Thanks for your interest in FastFormers! There's one assumption that is not valid for head pruned attention modules. (`hidden_size != head_size * num_heads`, because `head_size` is fixed and some heads are pruned. So, `num_heads` is now smaller than the original value.). There seem to be a few places in HF transformers which rely on this assumption. 

If you could cherry-pick the changes in `modeling_bert.py` and `configuration_bert.py` from the PR in HR repo, you might be able to execute the fastformers example script.

Hope this answers your question. And, please let me know if you have any other questions. Thanks!

**Comment by jmwoloso** [comment]
Thanks for the reply @ykim362! That's pretty interesting. I'm still reading through the paper, but is that the only real hangup preventing your work from being merged to Transformers?

**Comment by ykim362** [comment]
@jmwoloso that was a major blocking issue. The other things are more about pipelining of datasets based on applications which also need some work. But, those are more related to the applications.

**Comment by jmwoloso** [comment]
ok, thank you for the detail @ykim362!
